### ISSUE TITLE
Get new calibration parameters after calibration procedure

### ISSUE THREAD

**Issue by Romain123456** [doughtmw/display-calibration-hololens#1]
Hi !
I'm trying to calibrate my hololens 2 camera following the procedure of the hmd calib scene. 
My options of NetworkBehavior.cs are :
ArUco Tracking Type : Markers
ArUco Tracking Type after calibration : Custom Board
Calibration Parameter Type : User Defined
HMD Calibration Type : Point Based

I localize all points for both eyes but is there a way to obtain new camera calibration params from these results ?
Thanks a lot for your help !

**Comment by doughtmw** [comment]
Hi @Romain123456, thanks for your interest in the work. After the manual display calibration procedure, the estimated transform for the right and left eyes will be applied to the marker/board transform to ensure that the tracking position is corrected based on your input and preference in aligning the tracked marker with the on-screen reticle:

https://github.com/doughtmw/display-calibration-hololens/blob/861dba8cac885eea2bb4540fe02cb632f2744170/unity-sandbox/HoloLens2-Display-Calibration/Assets/Scripts/NetworkBehaviour.cs#L715-L717

https://github.com/doughtmw/display-calibration-hololens/blob/861dba8cac885eea2bb4540fe02cb632f2744170/unity-sandbox/HoloLens2-Display-Calibration/Assets/Scripts/NetworkBehaviour.cs#L592-L594

If you would like to get the transform from display calibration (`CollectPointCorrespondences.CalibMatrixLeft` and `CollectPointCorrespondences.CalibMatrixRight` from above) you can simply print it to the Unity console, then copy it into the `PredefinedTransform` script attached to the `ScriptHolder` game object (as in below image), and then on `NetworkBehaviour` under `HMDCalibrationType` select the `UserDefined` dropdown option. In this way, you can re-use the display calibration parameters from a prior calibration session for a new session (though I would advise against this as it may not lead to the best tracking accuracy). 

![image](https://user-images.githubusercontent.com/25186390/152377367-40e8dcfa-caa5-4900-81e2-e6f2c66e4873.png)

I also noticed that on the `NetworkBehaviour` script, you selected the `CalibrationParameterType` as `UserDefined`. Unless you have gone through a camera calibration procedure for your specific HoloLens 2 device (different from the manual display calibration procedure with the tracked marker), I would recommend that you change this to the default option of `PerFrame` to use the per-frame intrinsic parameters provided by the HoloLens 2 device. There are more details available on a camera calibration procedure of the HoloLens 2 [available on another repo of mine](https://github.com/doughtmw/ArUcoDetectionHoloLens-Unity#:~:text=Camera%20calibration%20for%20the%20HoloLens%202).

**Comment by Romain123456** [comment]
Thanks for your answer ! 
I also have used your other camera calibration procedure with chessboard pictures and python routines, but I find wrong values in the Principal Point and I have an important bias between markers and holograms. Manually changes of the Principal Point values correct the bias. But I want to better determine my calibration values !

Following your advice, I obtain these coefficients :
CollectPointCorrespondences.CalibMatrixRight : 
0.99856	0.03017	0.04434	0.01787
-0.03438	0.99464	0.09747	0.01817
-0.04116	-0.09886	0.99425	-0.00456
0.00000	0.00000	0.00000	1.00000
The hologram cube verifying the calibration shows a good accuracy with the marker ! However, I would want to get the focals points and principal points. From these coefficients, is there a way to retrieve these values ? 
Thanks again for your help !

**Comment by doughtmw** [comment]
Glad that it's working! You can access the per-frame camera intrinsic parameters here:
https://github.com/doughtmw/display-calibration-hololens/blob/861dba8cac885eea2bb4540fe02cb632f2744170/unity-sandbox/HoloLens2-Display-Calibration/Assets/Scripts/NetworkBehaviour.cs#L357-L366

**Comment by Romain123456** [comment]
Hi @doughtmw, it works very nice and I obtain values near ones I manually entered. I can validate the calibration ! Thanks for your work and your help !

Just a precision concerning the Debug.Log if it can help someone : I had to print separately the different parameters of calibParams (mediaFrameReference.VideoMediaFrame.CameraIntrinsics.FocalLength, mediaFrameReference.VideoMediaFrame.CameraIntrinsics.PrincipalPoint...), the line Debug.Log($"Per-frame calibParams: [{calibParams}]"); has for results : Per-frame calibParams: [OpenCVRuntimeComponent.CameraCalibrationParams]
